version: "3.1"
services:
  db-mysql:
    image: mysql:5.7
    platform: linux/x86_64
    container_name: database-mysql
    # command: --default-authentication-plugin=mysql_native_password
    restart: always
    env_file: ./.env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PROD_PASS}
      # MYSQL_USER: ${MSYQL_PROD_USER}
      # MYSQL_PASSWORD: ${MYSQL_PROD_PASS}
      MYSQL_DATABASE: ${MYSQL_PROD_DATABASE}
    ports:
      - ${MYSQL_PROD_PORT}:${MYSQL_DOCKER_PORT}
    volumes:
      - ./db/database.sql:/docker-entrypoint-initdb.d/database.sql:rw
      - mysql_db_data_container:/var/lib/mysql:rw

  server:
    build: .
    env_file: ./.env
    image: backend/rest
    container_name: backend-rest
    restart: unless-stopped
    links:
      - db-mysql:db-mysql
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - db-mysql
volumes:
  mysql_db_data_container:
    driver: local
